### ISSUE TITLE
Board will not load: "Inconsistent indentation"

### ISSUE THREAD

**Issue by jameshochadel** [cwru-hvz-core/cwru-hvz-source#76]
Error from Airbrake:
Inconsistent indentation: 9 spaces used for indentation, but the rest of the document was indented using 2 spaces.

Where:
games#show

File:
/home/hvz/cwru-hvz-source/app/views/games/show.html.haml, line 129

**Comment by jameshochadel** [comment]
Fixed by PR #81. Resolving.

**Comment by tdooner** [comment]
You may want to look into using some linters, like [haml-lint](https://github.com/brigade/haml-lint) to avoid errors like this in the future. Also [overcommit](https://github.com/brigade/overcommit) is helpful at automating the running of linters at commit-time.

**Comment by jameshochadel** [comment]
Good idea. I'll add it to the dev environment setup documentation to start, and I'm going to try automatically running linters and related code quality tools using Code Climate on all PRs to master.
